### ISSUE TITLE
Onboarding flow on initial launch can crash app using a physical device

### ISSUE THREAD

**Issue by tfrank64** [IBM-MIL/IBM-Ready-App-for-Loyalty#11]
The cause it most definitely memory pressure due to sequence of images creating the 3 animations.

**Comment by nhekman** [comment]
Also can cause crash by tapping "tutorial" in settings page (same animations)

**Comment by trishayy** [comment]
Seems to be fixed after freeing up some memory by changing images from pdfs to pngs. Can no longer reproduce.
