### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by dufengibm** [IBM-MIL/IBM-Ready-App-for-Loyalty#32]
Start the App, the first page we will see the "Network Error" warning on the top. when we click "CHEAPEST"  or "CLOSEST", the app will crash. Not sure whether the China network problem, please help check, thanks.
![img_0262](https://cloud.githubusercontent.com/assets/5977348/11549758/db08f73c-99a3-11e5-8f6c-4dcfe56a35d9.PNG)

**Comment by nhekman** [comment]
@dufengibm make sure the values in the .plist files are configured in the ReadyAppiOS/Loyalty/Configuration directory. This should resolve any network errors.

**Comment by nhekman** [comment]
@trishayy we should still ensure that the app doesn't crash if no network connection and user taps CLOSEST or CHEAPEST (disable user interaction on these buttons until loading is done)

**Comment by nhekman** [comment]
Fixed in Commit 928b770. Marking this issue as closed.
